"""make_contents.py -- list what is inside every pack, and check nothing odd got in.

Double-click it, or run it from a console. It looks for a "packs" folder next to
itself and writes "packs/CONTENTS.md".

WHY THIS EXISTS
    README.md tells people, in the section headed "here's what's checkable
    rather than just claimed":

        There is no installer and no executable. Every pack contains only .dds
        textures, .zms mesh geometry, .cur cursors, .css and .html, and .txt
        readmes. Nothing in these archives can run.

        Everything is browsable right here.

    The second claim needs something to browse, and GitHub cannot show anyone
    inside a zip. The first claim has never actually been verified across all
    of the packs -- it has only been true because the packs were built
    carefully.

    So this does both. It writes one page listing every file in every pack, and
    it refuses to pretend everything is fine if it finds a file type that
    should not be in there.

WHAT IT TOUCHES
    It writes exactly one file: packs/CONTENTS.md. Everything else is read.
    Nothing is extracted, nothing is deleted, and the zips are opened read-only.

    Re-run it whenever the packs change. It replaces the page rather than
    adding to it, so running it twice is the same as running it once.

    Standard library only. Nothing to install.
"""

import os
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
PACKS = os.path.join(HERE, 'packs')
PAGE = os.path.join(PACKS, 'CONTENTS.md')

# What a pack is allowed to contain.
#
# This list was originally copied from the README's claim and immediately
# failed against real packs -- because the README's list was incomplete, not
# because anything was wrong with the packs. The engine file types below are
# all ordinary mod content:
#
#   .dds  textures            .ptl  particle definitions
#   .zms  mesh geometry       .zmo  motion / animation
#   .cur  cursors             .eft  effect definitions
#   .css .html .txt .md .json  plain text and data
#   .png                      preview images
#
# The point of the list is that anything NOT on it gets a human look. Do not
# widen it just to make the report go quiet -- that turns the check into
# decoration.
ALLOWED = {'.dds', '.zms', '.zmo', '.eft', '.ptl', '.cur',
           '.css', '.html', '.txt', '.md', '.json', '.png'}

# Things that must never be in a mod pack, called out by name so the report
# says WHY rather than just "unexpected".
DANGEROUS = {'.exe', '.dll', '.bat', '.cmd', '.ps1', '.vbs', '.scr', '.msi',
             '.com', '.jar', '.py', '.sh', '.reg'}


def read_pack(path):
    """Every real file inside one zip, with its size. Nothing is extracted.

    Folder entries are skipped -- a zip records them separately and they are
    not files anyone receives.
    """
    files = []
    with zipfile.ZipFile(path) as archive:
        for entry in archive.infolist():
            if entry.is_dir():
                continue
            files.append((entry.filename.replace('\\', '/'), entry.file_size))
    files.sort(key=lambda pair: pair[0].lower())
    return files


def check(files):
    """Anything in this pack worth a human look.

    Three buckets, because they mean three different things:

      dangerous  -- something that can execute. Stop everything.
      nested     -- a zip inside the pack. Normal for a bundle like
                    FunBeams_All24, worth stating rather than hiding.
      unexpected -- a file type nobody has vouched for. Usually a new
                    legitimate format; occasionally a mistake.
    """
    dangerous, nested, unexpected = [], [], []
    for name, _size in files:
        suffix = os.path.splitext(name)[1].lower()
        if suffix in DANGEROUS:
            dangerous.append(name)
        elif suffix == '.zip':
            nested.append(name)
        elif suffix not in ALLOWED:
            unexpected.append(name)
    return dangerous, nested, unexpected


def pretty(size):
    if size >= 1024 * 1024:
        return '%.1f MB' % (size / 1024.0 / 1024)
    if size >= 1024:
        return '%.0f KB' % (size / 1024.0)
    return '%d bytes' % size


def build():
    if not os.path.isdir(PACKS):
        print('No "packs" folder next to this script.')
        print('Put make_contents.py in the same folder as packs/ and run it again.')
        return 1

    zips = sorted(name for name in os.listdir(PACKS) if name.lower().endswith('.zip'))
    if not zips:
        print('No zips found in %s' % PACKS)
        return 1

    lines = [
        '# What is inside every pack',
        '',
        'Every file in every download, listed straight out of the archives.',
        'Nothing here can run: no `.exe`, no `.dll`, no scripts, no installer.',
        '',
        'This page is generated by `make_contents.py`. Do not edit it by hand --',
        're-run the script instead.',
        '',
        '---',
        '',
        'CONTENTS_SUMMARY',
        '',
        '---',
        '',
    ]

    total_files = 0
    problems = []
    bundles = []
    # What file types actually turn up, counted rather than remembered. The
    # README has to state this and stating it from memory is how it came to be
    # wrong in the first place.
    kinds = {}

    for name in zips:
        path = os.path.join(PACKS, name)
        try:
            files = read_pack(path)
        except (zipfile.BadZipFile, OSError) as trouble:
            problems.append((name, 'could not be opened: %s' % trouble))
            print('COULD NOT READ  %s -- %s' % (name, trouble))
            continue

        dangerous, nested, unexpected = check(files)
        if dangerous:
            problems.append((name, 'CAN EXECUTE: %s' % ', '.join(dangerous)))
        if unexpected:
            problems.append((name, 'unvouched file type: %s' % ', '.join(unexpected)))
        if nested:
            bundles.append((name, len(nested)))

        for filename, _size in files:
            suffix = os.path.splitext(filename)[1].lower() or '(no extension)'
            kinds[suffix] = kinds.get(suffix, 0) + 1

        total_files += len(files)
        biggest = max((size for _n, size in files), default=0)

        # <details> collapses on GitHub, so the page stays short until someone
        # opens the pack they care about. Ctrl+F still searches inside all of
        # them at once, which a folder tree would not allow.
        lines.append('<details>')
        lines.append('<summary><b>%s</b> &mdash; %d files, largest %s</summary>'
                     % (name, len(files), pretty(biggest)))
        lines.append('')
        lines.append('```')
        for filename, _size in files:
            lines.append(filename)
        lines.append('```')
        lines.append('</details>')
        lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('%d packs, %d files in total.' % (len(zips), total_files))
    lines.append('')
    lines.append('Every file type present, counted:')
    lines.append('')
    for suffix, count in sorted(kinds.items(), key=lambda pair: -pair[1]):
        lines.append('- `%s` &mdash; %d' % (suffix, count))
    lines.append('')

    summary = 'File types present: ' + ', '.join(
        '`%s` (%d)' % (suffix, count)
        for suffix, count in sorted(kinds.items(), key=lambda pair: -pair[1]))
    page = '\n'.join(lines).replace('CONTENTS_SUMMARY', summary)

    with open(PAGE, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(page)

    print('Read %d packs, %d files.' % (len(zips), total_files))
    print('Wrote %s' % PAGE)
    print()

    for name, count in bundles:
        print('  note: %s holds %d packs inside it (a bundle).' % (name, count))
    if bundles:
        print()

    if problems:
        print('=' * 60)
        print('%d PACK(S) NEED LOOKING AT:' % len(problems))
        for name, why in problems:
            print('  %-40s %s' % (name, why))
        print()
        print('Nothing above can run unless it says CAN EXECUTE.')
        print('An unvouched type is usually a legitimate format this script has')
        print('not been told about -- check it, then add it to ALLOWED.')
        print('=' * 60)
        return 2

    print('Nothing can execute. Every file is a vouched-for type.')
    print()
    print('File types present, for the README:')
    for suffix, count in sorted(kinds.items(), key=lambda pair: -pair[1]):
        print('  %-16s %d' % (suffix, count))
    return 0


if __name__ == '__main__':
    code = build()
    # Double-clicked, the console would close before any of this could be read.
    if sys.stdin and sys.stdin.isatty():
        try:
            input('\nPress Enter to close.')
        except (EOFError, KeyboardInterrupt):
            pass
    sys.exit(code)
